# Generated by Django 5.0.6 on 2024-11-14 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0002_profile_delete_userpr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_resume', models.CharField(help_text='Резюме на тему...', max_length=100)),
                ('desire_pos', models.CharField(help_text='На якій посаді бажаєте бути?', max_length=100)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Яку я хочу зарплату', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Резюме', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_bio', models.CharField(help_text='ПІБ', max_length=50)),
                ('phone', models.CharField(blank=True, help_text='Номер телефону', max_length=13)),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна почта')),
                ('adress', models.CharField(help_text='Ваше місто', max_length=100)),
                ('hb_date', models.DateField(blank=True, help_text='Дата народження', null=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_about_user', to='myresume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Назва посади', max_length=100)),
                ('company_name', models.CharField(help_text='Назва компанії', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Залиште порожнім, якщо ще працюєте', null=True)),
                ('responsibilities', models.TextField(blank=True, help_text="Основні обов'язки")),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='myresume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='AddInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.TextField(blank=True, help_text='Інтереси та хобі')),
                ('personal_qualities', models.TextField(blank=True, help_text='Особисті якості')),
                ('achievements', models.TextField(blank=True, help_text='Досягнення')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_info', to='myresume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.TextField(help_text='Опис ваших навичок', max_length=200)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='myresume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(help_text='Назва навчального закладу', max_length=100)),
                ('qualification_lvl', models.CharField(help_text='Кваліфікація або спеціальність', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Дата закінчення навчального закладу', null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eductions', to='myresume.resume')),
            ],
        ),
    ]
