# Generated by Django 5.1.3 on 2024-11-28 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0003_resume_infouser_experience_addinfo_skill_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Назва посади', max_length=100)),
                ('company_name', models.CharField(help_text='Назва компанії', max_length=100)),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата закінчення')),
                ('responsibilities', models.TextField(blank=True, help_text='Детальніше')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='myresume.resume')),
            ],
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
