# Generated by Django 5.1.3 on 2024-12-12 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0004_workexperience_delete_experience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infouser',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='title_resume',
        ),
        migrations.AddField(
            model_name='infouser',
            name='address',
            field=models.CharField(blank=True, help_text='Ваше місто', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='resume_photos/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(blank=True, help_text='Резюме на тему...', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='desire_pos',
            field=models.CharField(blank=True, help_text='На якій посаді бажаєте бути?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(help_text='Опис ваших навичок', max_length=200),
        ),
        migrations.AlterField(
            model_name='study',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='myresume.resume'),
        ),
    ]
