# Generated by Django 5.1.3 on 2024-12-14 09:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0005_remove_infouser_adress_remove_resume_title_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addinfo',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AddInfo', to='myresume.resume'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Додаткова інформація', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='desire_pos',
            field=models.CharField(help_text='На яку посаду ви претендуєте?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(blank=True, help_text='Інформація про освіту', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(help_text='Електронна пошта', max_length=254, validators=[django.core.validators.EmailValidator(message='Введіть дійсну електронну пошту.')]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(blank=True, help_text='Ваш професійний досвід', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='first_name',
            field=models.CharField(help_text="Ваше ім'я", max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='last_name',
            field=models.CharField(help_text='Ваше прізвище', max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(help_text='Контактний номер телефону', max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='Введіть правильний номер телефону.')]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='photo',
            field=models.ImageField(blank=True, help_text='Ваше фото', upload_to='resume_photos/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Очікувана заробітна плата', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(help_text='Резюме на тему...', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(help_text='Назва навички', max_length=100),
        ),
        migrations.AlterField(
            model_name='study',
            name='end_date',
            field=models.DateField(blank=True, help_text='Дата завершення навчання', null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='institution_name',
            field=models.CharField(help_text='Навчальний заклад', max_length=100),
        ),
        migrations.AlterField(
            model_name='study',
            name='qualification_lvl',
            field=models.CharField(help_text='Кваліфікація/спеціальність', max_length=100),
        ),
        migrations.AlterField(
            model_name='study',
            name='start_date',
            field=models.DateField(help_text='Дата початку навчання'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company_name',
            field=models.CharField(help_text='Компанія', max_length=100),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, help_text='Дата завершення', null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='job_title',
            field=models.CharField(help_text='Посада', max_length=100),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='responsibilities',
            field=models.TextField(blank=True, help_text="Обов'язки або досягнення"),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='myresume.resume'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(help_text='Дата початку'),
        ),
        migrations.DeleteModel(
            name='InfoUser',
        ),
    ]
