# Generated by Django 5.1.3 on 2024-12-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0006_alter_addinfo_resume_alter_resume_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, help_text='Електронна пошта', max_length=254, null=True),
        ),
    ]
