# Generated by Django 5.1.3 on 2024-12-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0007_alter_resume_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='user',
            new_name='owner',
        ),
    ]
